name: Deploy to Pacha Family
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_PERCOLOUCO }}
          username: ${{ secrets.FTP_USERNAME_PERCOLOUCO }}
          password: ${{ secrets.FTP_PASSWORD_PERCOLOUCO }}
          local-dir: ./
          server-dir: /www/househub/ # ← Production reste ici
